# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywUCsi2Mni9uBN11QvYGm4FAp0kGRzPM
"""



"""# **Project Name :-  Hotel Booking Analysis**
Project type - EDA

Contribution - individual

# **Project** **Summary** -
  Hotel booking analysis is a study of the data related to hotel bookings. This type of analysis is crucial for the hospitality industry as it helps to understand the demand for hotel rooms and the factors that influence booking decisions. The goal of hotel booking analysis is to gain insights into customer behavior and preferences, as well as to identify trends and patterns in hotel booking data.

  The data used for hotel booking analysis is typically collected from a variety of sources, including hotel reservation systems, customer databases, and online travel agencies. The data may include information on the date of the booking, the type of room, the length of stay, the customer's location, and demographic information.

  One of the first steps in hotel booking analysis is data cleaning and preparation. This involves checking the data for errors, missing values, and inconsistencies, and then transforming the data into a usable format. This may involve converting categorical variables into numerical values, aggregating data by group, and removing outliers.

Once the data has been cleaned and prepared, the next step is to perform exploratory data analysis. This involves summarizing and visualizing the data to identify patterns, trends, and relationships between variables. For example, a hotel booking analyst may look at the relationship between the time of year and the number of bookings, or the relationship between room type and customer demographics.

After exploratory data analysis, the next step is to perform statistical analysis. This may include regression analysis, time series analysis, and cluster analysis. The goal of statistical analysis is to identify the factors that influence hotel booking decisions, such as customer demographics, room type, and seasonality. For example, a hotel booking analyst may use regression analysis to determine the relationship between customer income and the likelihood of booking a room, or use cluster analysis to group customers into segments based on their booking behavior.

Another important aspect of hotel booking analysis is the use of machine learning algorithms. Machine learning algorithms can be used to predict customer behavior, such as the likelihood of booking a room, or the likelihood of booking a room in the future. These predictions can be used to optimize pricing and marketing strategies, as well as to improve customer experience. For example, a hotel booking analyst may use a machine learning algorithm to predict the likelihood of a customer booking a room based on their previous booking behavior, and then use this information to target marketing efforts to high-value customers.

The results of hotel booking analysis can be used to make data-driven decisions in the hospitality industry. For example, a hotel booking analyst may use the results of their analysis to optimize pricing strategies, improve customer experience, and enhance marketing efforts. The insights gained from hotel booking analysis can also be used to inform investment decisions, such as the decision to build new hotels in certain locations or to expand existing hotel properties.

In conclusion, hotel booking analysis is a crucial tool for the hospitality industry. It helps to understand customer behavior and preferences, identify trends and patterns in hotel booking data, and make data-driven decisions. By using a combination of data cleaning and preparation, exploratory data analysis, statistical analysis, and machine learning algorithms, hotel booking analysts can gain valuable insights into the factors that influence hotel booking decisions and use this information to optimize pricing, marketing, and customer experience strategies.

# **Problem** **Statement**
 This data contains booking information for a city hotel and a resort hotel and includes information such as how many peoples are come, number of children, number of adults, number of babies, number of avaliable parking spaces, length of stay.
  
  The main objective behind this project is to explore and analyze data to discover more important factors that govern the bookings and give insights of hotel management which can various campaigns to boost the business and performance.
"""

# Commented out IPython magic to ensure Python compatibility.
# import libraries

import numpy as np
import pandas as pd
import matplotlib as mt
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as ply
import altair as alt
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/Abhishek/Hotel Bookings.csv'
df = pd.read_csv(path)
pd.set_option('display.max_columns',None)
df

df['total stays'] = df['stays_in_week_nights'] + df['stays_in_weekend_nights']

df['total people'] = df['adults'] + df['babies'] + df['children']

df.fillna(0, inplace=True)
df

df.shape

df.info()

df.duplicated().sum()

a = df.isnull().sum()
a

a.plot(kind = 'bar')
plt.rcParams['figure.figsize'] = (30,30)
plt.title('Visualizing null values',fontsize = 50)
plt.xlabel('Columns',fontsize = 30)
plt.ylabel('value counts',fontsize = 30)

"""## There are 1,19,390 rows and 32 columns in this dataset and 31,994 duplicate values in this datset and some columns such as in 'country' column there are 488 null values, in 'agent' column there are 16340 and in 'company' column there are 1,12,593 null values are present. According to above bar graph 'company' column contains more null values as compared to the other two columns (country and agent) and remaining all other remaining columns does not contains any null values."""

list(df.columns)

df.describe()

df

"""# ***Variable Discription***


# **Hotel** :-  H1= Resort Hotel,  H2=City Hotel

# **is_cancelled** :- If the booking was cancelled(1) or not(0)

# **lead_time** :- Number of days that elapsed between the entering date of the booking into the PMS and the arrival date

# **arrival_date_year** :- Year of arrival date

# **arrival_date_month** :- Month of arrival date

# **arrival_date_week_number** :- Week number for arrival date

# **arrival_dat_day** :-  Day of arrival date

# **stays_in_weekend_nights** :- Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel

# **stays_in_week_nights** :- Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel

# **adults** :-  Number of adults

# **children** :-  Number of children

# **babies** :-  Number of babies

# **meal** :-  Kind of meal opted for

# **country** :-  Country code

# **market_segment** :-  Which segment the customer belongs to

# **Distribution_channel** :-  How the customer accessed the stay corporate booking/Direct/TA.TO

# **is_repeated_guest** :-  Guest coming for first time or not

# **previous_cancellation** :-   Was there a cancellation before

# **previous_bookings** :-   Count of previous bookings

# **reserved_room_type** :-  Type of room reserved

# **assigned_room_type** :-  Type of room assigned

# **booking_changes** :-  Count of changes made to booking

# **deposit_type** :-  Deposit type

# **agent_Booked**  :-  through agent

# **days_in_waiting_list** :-  Number of days in waiting list

# **customer_type** :-  Type of customer

# **required_car_parking** :-  If car parking is required

# **total_of_special_req** :-  Number of additional special requirements

# **reservation_status** :-  Reservation of status

# **reservation_status_date** :-  Date of the specific status





"""

R_hotel = df[df['hotel'].str.contains('Resort Hotel')]
R_hotel.rename(columns={'total people':'total people in Resort hotel'},inplace=True)
R_hotel.rename(columns={'is_canceled':'cancellations in R_hotel'},inplace=True)
R_hotel.rename(columns={'total stays':'total stays in R_hotel'},inplace=True)
R_hotel

C_hotel = df[df['hotel'].str.contains('City Hotel')]
C_hotel.rename(columns={'total people':'total people in city hotel'},inplace = True)
C_hotel.rename(columns={'is_canceled':'cancellations in C_hotel'},inplace=True)
C_hotel.rename(columns={'total stays':'total stays in C_hotel'},inplace=True)
C_hotel

booking_hotel = df["hotel"].value_counts()

plt.pie(booking_hotel, labels = booking_hotel.index,radius=2);

plt.figure(figsize=(15,5))
sns.countplot(x='meal',hue='hotel',data=df)

plt.figure(figsize=(15,5))
sns.set(font_scale = 1)
sns.countplot(df.reserved_room_type)

sns.countplot(df.arrival_date_year)

plt.figure(figsize=(15,5))
sns.countplot(x='market_segment',hue='hotel',data=df)

sns.countplot(df.distribution_channel)

plt.figure(figsize=(15,5))
sns.countplot(x='arrival_date_month',hue='arrival_date_year',data=df)

sns.countplot(df.hotel)

plt.figure(figsize=(15,5))
sns.countplot(x='previous_cancellations',hue='hotel',data=df)

sns.countplot(df.customer_type)

plt.figure(figsize=(15,5))
sns.countplot(x='stays_in_weekend_nights',hue='hotel',data=df)

sns.countplot(df.reservation_status)

sns.countplot(df.deposit_type)

sns.countplot(df.is_canceled)

df.reservation_status.value_counts()

sns.countplot(df.total_of_special_requests)

sns.countplot(df.booking_changes)

df.hotel.value_counts()

plt.figure(figsize=(15,5))
sns.set(font_scale = 1)
sns.countplot(df.arrival_date_month)

plt.figure(figsize=(30,10))
sns.set(font_scale = 1)
sns.countplot(df.arrival_date_week_number)